name: Deploy to Hugging Face Space

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "ananttripathiak@gmail.com"
          git config user.name "ananttripathi"
          git remote add space https://ananttripathiak:${HF_TOKEN}@huggingface.co/spaces/ananttripathiak/pneumonia-detection-space
          git filter-branch --force --index-filter \
            "git rm --cached --ignore-unmatch models/saved_models/best_model.h5 models/saved_models/best_model.keras" \
            --prune-empty --tag-name-filter cat -- --all
          git push space main --force
